server:
  #服务端口号
  port: 8090
  #服务根路径--根据项目自行修改
  servlet.context-path: /lobster
lobster:
  test: @lobster.test@

spring.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: @spring.datasource.master.url@
    username: @spring.datasource.master.username@
    password: @spring.datasource.master.password@
  slave:
    url: @spring.datasource.slave.url@
    username: @spring.datasource.slave.username@
    password: @spring.datasource.slave.password@

